controllers/AuthController.php
<?php

namespace app\controllers;

use app\models\LoginForm;
use Yii;
use yii\web\Controller;

/**
 * AuthController implements the User (Login & Logout).
 */
class AuthController extends Controller 
{
    /**
     * User login page.
     * @return mixed
     */
    public function actionLogin()
    {

        $this->layout = false;
        
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['admin/news']);
        }

        $model = new LoginForm();
        
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['admin/news']);
        }

        $model->password = '';
        return $this->render('login', ['model' => $model]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(['/']);
    }

}

views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Url;
use yii\helpers\Html;
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Znews | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>

    <link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico">
    <?php $this->head() ?>

    <!-- Font Awesome -->
    <?php $this->registerCssFile('@web/AdminLTE/plugins/fontawesome-free/css/all.min.css') ?>
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <?php $this->registerCssFile('@web/AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') ?>
    <!-- iCheck -->
    <?php $this->registerCssFile('@web/AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css') ?>

    <!-- Theme style -->
    <?php $this->registerCssFile('@web/AdminLTE/dist/css/adminlte.min.css') ?>
    <!-- overlayScrollbars -->
    <?php $this->registerCssFile('@web/AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') ?>
    <?php $this->registerCssFile('@web/AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.css') ?>

    <?php $this->registerCssFile('@web/AdminLTE/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') ?>

    <?php $this->registerCssFile('@web/AdminLTE/plugins/croppie/croppie.css') ?>

    <?php $this->registerCssFile('@web/plugins/fancybox/dist/jquery.fancybox.min.css') ?>
    <?php $this->registerCssFile('@web/css/admin-css.css') ?>
    <?php $this->registerCssFile('@web/css/sizes.css') ?>

    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <?php $this->registerCssFile('@web/plugins/Validation-Engine/validationEngine.jquery.css') ?>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <?php $this->registerJsFile('@web/AdminLTE/plugins/datatables/jquery.dataTables.js') ?>

    <?php $this->registerJsFile('@web/AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.js') ?>


</head>
<body class="hold-transition sidebar-mini layout-fixed">
<?php $this->beginBody() ?>

<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="#" class="brand-link">
            <?= Html::img('@web/AdminLTE/dist/img/AdminLTELogo.png', ['alt' => 'AdminLTE Logo', 'class' => 'brand-image img-circle elevation-3', 'style' => 'opacity: .8']) ?>

            <span class="brand-text font-weight-light"><strong>Z</strong>NEWS</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <?php if (!empty(Yii::$app->user->identity->avatar) && file_exists('images/users/' . Yii::$app->user->identity->avatar)) { ?>
                        <?= Html::img('@web/images/users/' . Yii::$app->user->identity->avatar, ['alt' => 'admin', 'class' => 'img-circle elevation-2']) ?>
                    <?php } else { ?>
                        <?= Html::img('@web/images/no_avatar.png', ['alt' => 'admin', 'class' => 'img-circle elevation-2']) ?>
                    <?php } ?>
                </div>
                <div class="info">
                    <a href="#" class="d-block"><?= Yii::$app->user->identity->name . ' ' . Yii::$app->user->identity->surname ?> </a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                    <li class="nav-item">
                        <a href="<?= Url::toRoute('admin/category') ?>" class="nav-link <?= !empty($this->params['activePage']) && $this->params['activePage'] == 'category' ? 'active' : '' ?>">
                            <i class="nav-icon fas fa-list"></i>
                            <p>Categories</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="<?= Url::toRoute('admin/news') ?>" class="nav-link <?= !empty($this->params['activePage']) && $this->params['activePage'] == 'news' ? 'active' : '' ?>">
                            <i class="nav-icon far fa-newspaper"></i>
                            <p>News</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="<?= Url::toRoute('admin/contact') ?>"" class="nav-link <?= !empty($this->params['activePage']) && $this->params['activePage'] == 'contact' ? 'active' : '' ?>">
                            <i class="nav-icon fas fa-envelope"></i>
                            <p>Contact message</p>
                        </a>
                    </li>

                    <li class="nav-header">USER</li>

                    <li class="nav-item">
                        <a href="<?= Url::toRoute('admin/user') ?>" class="nav-link <?= !empty($this->params['activePage']) && $this->params['activePage'] == 'profile' ? 'active' : ''?>">
                            <i class="nav-icon far fa-user"></i>
                            <p>Profile</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" id="logout" data-text="Do you want to leave the admin-panel?" data-url="<?= Url::toRoute('auth/logout') ?>">
                            <i class="nav-icon fas fa-arrow-alt-circle-left"></i>
                            <p>Logout</p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>


    <?=$content?>


    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>Copyright &copy; 2014-2019<a href="http://adminlte.io">AdminLTE.io</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.0.0-rc.1
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery UI 1.11.4 -->
<?php $this->registerJsFile('@web/AdminLTE/plugins/jquery-ui/jquery-ui.min.js') ?>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<?php $this->registerJsFile('@web/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js') ?>

<?php $this->registerJsFile('@web/AdminLTE/plugins/sweetalert2/sweetalert2.min.js') ?>

<?php $this->registerJsFile('@web/AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') ?>
<!-- AdminLTE App -->
<?php $this->registerJsFile('@web/AdminLTE/dist/js/adminlte.js') ?>

<?php $this->registerJsFile('@web/plugins/Validation-Engine/jquery.validationEngine.js') ?>
<?php $this->registerJsFile('@web/plugins/Validation-Engine/jquery.validationEngine-en.js') ?>

<?php $this->registerJsFile('@web/AdminLTE/plugins/croppie/croppie.js') ?>
<?php $this->registerJsFile('@web/plugins/fancybox/dist/jquery.fancybox.min.js') ?>
<?php $this->registerJsFile('@web/js/admin-js.js') ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/public.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Url;
use yii\helpers\Html;
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Znews - IT news </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <?php $this->head() ?>


    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico">

    <!-- All css files are included here. -->
    <!-- Bootstrap fremwork main css -->
    <?php $this->registerCssFile('@web/css/bootstrap.min.css') ?>

    <!-- This core.css file contents all plugings css file. -->
    <?php $this->registerCssFile('@web/css/core.css') ?>

    <!-- Theme shortcodes/elements style -->
    <?php $this->registerCssFile('@web/css/shortcode/shortcodes.css') ?>

    <!-- Theme main style -->
    <?php $this->registerCssFile('@web/css/style.css') ?>

    <!-- Responsive css -->
    <?php $this->registerCssFile('@web/css/responsive.css') ?>

    <!-- User style -->
    <?php $this->registerCssFile('@web/css/custom.css') ?>

    <?php $this->registerCssFile('@web/plugins/Validation-Engine/validationEngine.jquery.css') ?>

    <?php $this->registerCssFile('@web/AdminLTE/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') ?>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <!-- Modernizr JS -->
    <?php $this->registerJsFile('@web/js/vendor/modernizr-2.8.3.min.js') ?>
</head>
<body>
    <?php $this->beginBody() ?>

    <!--  THEME PRELOADER AREA -->
    <div id="preloader-wrapper">
        <div class="preloader-wave-effect"></div>
    </div>
    <!-- THEME PRELOADER AREA END -->

    <!-- Body main wrapper start -->
    <div class="wrapper">
        <!-- Start of header area -->
        <header  class="header-area header-wrapper bg-white clearfix">
            <!-- Start Sidebar Menu -->
            <div class="sidebar-menu">
                <div class="sidebar-menu-inner"></div>
                <span class="fa fa-remove"></span>
            </div>
            <!-- End Sidebar Menu -->

            <div class="header-middle-area">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-lg-4 col-sm-5 col-xs-12 header-mdh">
                            <div class="global-table">
                                <div class="global-row">
                                    <div class="global-cell">
                                        <div class="logo">
                                            <a href="<?= Url::toRoute('/') ?>">
                                                <?= Html::img('@web/images/logo/1.png', ['alt' => 'main logo'])?>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div id="sticky-header" class="header-bottom-area hidden-sm hidden-xs">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="menu-wrapper  bg-theme clearfix">
                                <div class="row">
                                    <div class="col-md-11">
                                        <div class="mainmenu-area">
                                            <nav class="primary-menu uppercase">
                                                <ul class="clearfix">
                                                    <li><a href="<?= Url::toRoute('/') ?>">Home</a></li>
                                                    <li><a href="<?= Url::toRoute('news') ?>">News</a></li>
                                                    <li><a href="<?= Url::toRoute('contact') ?>">Contact</a></li>
                                                </ul>
                                            </nav>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- mobile-menu-area start -->
            <div class="mobile-menu-area hidden-md hidden-lg">
                <div class="fluid-container">
                    <nav id="mobile_dropdown">
                        <ul>
                            <li><a href="<?= Url::toRoute('/') ?>">Home</a></li>
                            <li><a href="<?= Url::toRoute('news') ?>">News</a></li>
                            <li><a href="<?= Url::toRoute('contact') ?>">Contact</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
    </div>
    <!-- mobile-menu-area end -->
    </header>
    <!-- End of header area -->

    <?= $content ?>

    <!-- Start footer area -->
    <footer id="footer" class="footer-wrapper footer-1">
        <!-- Start footer top area -->
        <div class="footer-top-wrap ptb-70 bg-dark">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-5 hidden-sm">
                        <div class="zm-widget pr-40">
                            <h2 class="h6 zm-widget-title uppercase text-white mb-30">About Znews</h2>
                            <div class="zm-widget-content">
                                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
                                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-6 col-lg-3">
                        <div class="zm-widget">
                            <h2 class="h6 zm-widget-title uppercase text-white mb-30">Social Links</h2>
                            <div class="zm-widget-content">
                                <div class="zm-social-media zm-social-1">
                                    <ul>
                                        <li><a href="https://www.facebook.com"><i class="fa fa-facebook"></i>Like us on Facebook</a></li>
                                        <li><a href="https://twitter.com"><i class="fa fa-twitter"></i>Tweet us on Twitter</a></li>
                                        <li><a href="https://www.pinterest.com/"><i class="fa fa-pinterest"></i>Pin us on Pinterest</a></li>
                                        <li><a href="https://www.instagram.com/"><i class="fa fa-instagram"></i>Heart us on Instagram</a></li>
                                        <li><a href="https://plus.google.com"><i class="fa fa-google-plus"></i>Share us on GooglePlus</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-4 col-md-6 col-lg-4">
                        <div class="zm-widget">
                            <h2 class="h6 zm-widget-title uppercase text-white mb-30">Contact</h2>
                            <!-- Start Subscribe From -->
                            <div class="zm-widget-content">
                                <div class="subscribe-form subscribe-footer">
                                    <p>If you have any questions you can contact us.</p>
                                    <a href="<?= Url::toRoute('contact') ?>" class="contact-us"> Contact us</a>
                                </div>
                            </div>
                            <!-- End Subscribe From -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End footer top area -->
        <div class="footer-buttom bg-black ptb-15">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="zm-copyright text-center">
                            <p class="uppercase">© <?=date('Y')?> Your Company. All Rights Reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer area -->
    </div>
    <!-- Body main wrapper end -->

    <!-- Placed js at the end of the document so the pages load faster -->
    <!-- jquery latest version -->
    <?php $this->registerJsFile('@web/js/vendor/jquery-1.12.1.min.js') ?>

    <!-- Bootstrap framework js -->
    <?php $this->registerJsFile('@web/js/bootstrap.min.js') ?>

    <!-- All js plugins included in this file. -->
    <?php $this->registerJsFile('@web/js/owl.carousel.min.js') ?>
    <?php $this->registerJsFile('@web/js/plugins.js') ?>

    <!-- Main js file that contents all jQuery plugins activation. -->
    <?php $this->registerJsFile('@web/js/main.js') ?>
    <?php $this->registerJsFile('@web/AdminLTE/plugins/sweetalert2/sweetalert2.min.js') ?>
    <?php $this->registerJsFile('@web/plugins/Validation-Engine/jquery.validationEngine.js') ?>
    <?php $this->registerJsFile('@web/plugins/Validation-Engine/jquery.validationEngine-en.js') ?>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>