controllers/PageController.php
<?php


namespace app\controllers;

use app\helpers\MyUrl;
use app\models\Contact;
use app\models\News;
use Yii;
use yii\data\Pagination;
use yii\db\Expression;
use yii\web\Controller;

class PageController  extends Controller
{

    /**
     * Show Home page.
     * @return mixed
     */
    public function actionIndex()
    {
        $data = [
            'news'         => News::find()->with('category')->where(['is_published' => 1])->orderBy(['date_publish' => SORT_DESC])->limit(10)->all(),
            'most_popular' => News::find()->where(['is_published' => 1])->orderBy(['views' => SORT_DESC])->limit(6)->all(),
            'must_read'    => News::find()->with('category')->where(['is_must_read' => 1])->where(['is_published' => 1])->orderBy(['date_publish' => SORT_DESC])->limit(6)->all()
        ];

        return $this->render('index', $data);
    }

    /**
     * Show News page.
     * @param string $category
     * @return mixed
     */
    public function actionNews($category = '')
    {
        if (!empty($category)) {
            $idCategory = MyUrl::getIdUrl($category);
            $news = News::find()->with('category')->where(['is_published' => 1])->where(['id_category' => $idCategory]);

        } else {
            $news = News::find()->with('category')->where(['is_published' => 1]);
        }

        $pagination = new Pagination([
           'defaultPageSize' => 10,
           'totalCount' => $news->count()
        ]);

        $news = $news->orderBy(['date_publish' => SORT_DESC])->offset($pagination->offset)->limit($pagination->limit)->all();

        $data = [
            'news'         => $news,
            'pagination'   => $pagination,
            'most_popular' => News::find()->where(['is_published' => 1])->orderBy(['views' => SORT_DESC])->limit(6)->all(),
        ];
        return $this->render('news', $data);
    }

    /**
     * Show News detail page.
     * @param $alias
     * @return mixed
     */
    public function actionNewsDetail($alias)
    {
        $id = MyUrl::getIdUrl($alias);

        $news = News::findOne($id);
        $news->views += 1;
        $news->save();

        $data = [
            'news'               => $news,
            'most_popular'       => News::find()->where(['is_published' => 1])->orderBy(['views' => SORT_DESC])->limit(6)->all(),
            'can_be_interesting' => News::find()->where(['!=', 'id_news', $id])->orderBy(new Expression('rand()'))->limit(3)->all(),
        ];

        return $this->render('news_detail', $data);

    }

    /**
     * Show Contact page.
     * @return mixed
     */
    public function actionContact()
    {
        return $this->render('contact');
    }

    /**
     * Save contact message.
     * @return mixed
     */
    public function actionSaveContact()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $contact = new Contact();
        $contact->name = Yii::$app->request->post('name');
        $contact->email = Yii::$app->request->post('email');
        $contact->phone = Yii::$app->request->post('phone');
        $contact->website = Yii::$app->request->post('website');
        $contact->message = Yii::$app->request->post('message');
        $contact->created_at = date('Y-m-d H:i:s');

        if (!$contact->save()) {
            if ($contact->hasErrors()) {
                Yii::$app->response->statusCode = 422;

                return [
                    'status' => 'error',
                    'errors' => $contact->getErrors(),
                ];
            }

        } else {
            Yii::$app->response->statusCode = 200;

            return [
                'status'  => 'success',
                'message' => "Contact message was added successfully",
            ];
        }
    }

    /**
     * Show Error page.
     * @return mixed
     */
    public function actionError()
    {
        return $this->render('error');
    }
}

views/page/contact.php
<?php

use yii\helpers\Url;
?>

<!-- Start page content -->
<section id="page-content" class="page-wrapper">
    <!-- Start contact address area  -->
    <div class="zm-section bg-white ptb-65">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-6 col-lg-4 col-sm-8">
                    <div class="section-title-2 mb-40">
                        <h3 class="inline-block uppercase">Contact Us</h3>
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <div class="single-address text-center">
                        <i class="fa fa-home" aria-hidden="true"></i>
                        <h4>Address</h4>
                        <p>str.Puskin, Balti, Moldova</p>

                    </div>
                </div>
                <div class="col-md-4 col-sm-4 xs-mt-30">
                    <div class="single-address text-center">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                        <h4 class="uppercase">Email Address</h4>
                        <p>test@admin.com</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4 xs-mt-30">
                    <div class="single-address text-center">
                        <i class="fa fa-phone" aria-hidden="true"></i>
                        <h4 class="uppercase">Phone Number</h4>
                        <p>+373 688 30 059</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End contact address area  -->
    <!-- Start Google Map area -->
    <div class="zm-section">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="google-map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1341.1688140573879!2d27.921054512065833!3d47.755505158688095!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDfCsDQ1JzE5LjgiTiAyN8KwNTUnMTguMyJF!5e0!3m2!1sru!2s!4v1578487025923!5m2!1sru!2s" width="100%" height="600px" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Google Map area -->
    <!-- Start contact message area -->
    <div class="zm-section bg-white pt-60 pb-40">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-4">
                    <div class="section-title-2 mb-40">
                        <h3 class="inline-block uppercase">Send Us A MEssage</h3>
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                    </div>
                </div>
            </div>
            <div class="message-box">
                <form action="<?= Url::toRoute('page/save-contact') ?>" id="contact-form" method="post">
                    <input type="hidden" name="_csrf" value="<?= Yii::$app->request->getCsrfToken() ?>" />
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" class="validate[required]" name="name" placeholder="Full Name*">
                            <input type="text" class="validate[required,custom[email]]" name="email" placeholder="Email Address*">
                            <input type="text" class="validate[required]" name="phone" placeholder="Phone Number">
                            <input type="text" class="validate[custom[url]]" name="website" placeholder="Website">
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea name="message" class="validate[required]" placeholder="Type your message..."></textarea>
                            <button class="submit-button" type="submit">Send Message</button>
                        </div>
                    </div>
                </form>
                <p class="form-messege"></p>
            </div>
        </div>
    </div>
    <!-- End contact message area -->
</section>
<!-- End page content -->

<script>
    $(document).ready(function() {
        var validation = $("#contact-form").validationEngine('attach',{promptPosition : "bottomLeft", maxErrorsPerField: 1, validateNonVisibleFields: true, updatePromptsPosition:true});

        $('#contact-form').on('submit', function (e) {
            e.preventDefault();
            if(!validation.validationEngine('validate')){
                return false;
            }

            var formData = new FormData(this);

            $.ajax({
                url : $(this).attr('action'),
                type : 'POST',
                dataType : 'JSON',
                cache: false,
                contentType: false,
                processData: false,
                data : formData,
                success : function(response){
                    if(response.status == 'success'){
                        $('#contact-form')[0].reset();
                        Swal.fire({
                            type: response.status,
                            title: 'Success',
                            text: response.message,
                        })
                    }
                },
                error : function (response) {
                    let errors = response.responseJSON.errors;
                    let firstKey = Object.keys(errors)[0];

                    Swal.fire({
                        type: 'error',
                        title: 'Oops...',
                        text: errors[firstKey][0],
                    })
                }
            });
        });
    });

</script>

views/page/error.php
<?php
use yii\helpers\Url;
?>

<!-- Start page content -->
<section id="page-content" class="page-wrapper">
    <div class="zm-section bg-color page-notfound-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-lg-12 col-xs-12">
                    <div class="page-notfound-inner">
                        <h1>4<span>0</span>4</h1>
                        <h4>Oops! That page can’t be found</h4>
                        <p>Sorry, but the page you are looking for does not existing</p>
                        <a href="<?= Url::toRoute('/') ?>" class="submit-button">go to home Page</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End page content -->

views/page/news.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;

?>

<section id="page-content" class="page-wrapper">
    <div class="zm-section bg-white pt-70 pb-40">
        <div class="container">
            <div class="row">
                <!-- Start left side -->
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-8 columns">
                    <div class="row mb-40">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="section-title">
                                <h2 class="h6 header-color inline-block uppercase">Latest News</h2>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="zm-posts">

                                <?php foreach ($news as $item) { ?>
                                    <article class="zm-post-lay-c zm-single-post clearfix">
                                        <div class="zm-post-thumb f-left">
                                            <a href="<?= Url::toRoute('news/' . $item['id_news'] . '-' . $item['alias']) ?>">
                                                <?= Html::img('@web/images/news/' . $item['image'], ['alt' =>  $item['title']]) ?>
                                            </a>
                                        </div>
                                        <div class="zm-post-dis f-right">
                                            <div class="zm-post-header">
                                                <div class="zm-category">
                                                    <a href="<?= Url::toRoute('news/category/' . $item['id_category'] . '-' . $item['category']['alias']) ?>" class="bg-cat-5 cat-btn">
                                                        <?= $item['category']['name'] ?>
                                                    </a>
                                                </div>
                                                <h2 class="zm-post-title">
                                                    <a href="<?= Url::toRoute('news/' . $item['id_news'] . '-' . $item['alias']) ?>"><?= $item['title'] ?></a>
                                                </h2>
                                                <div class="zm-post-meta">
                                                    <ul>
                                                        <li class="s-meta">Views: <?= $item['views'] ?></li>
                                                        <li class="s-meta"><?= date('F d, Y', strtotime($item['date_publish'])) ?></li>
                                                    </ul>
                                                </div>
                                                <div class="zm-post-content">
                                                    <p><?= $item['description'] ?></p>
                                                </div>
                                            </div>
                                        </div>
                                    </article>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End left side -->
                <?php if (!empty($most_popular)) { ?>
                    <!-- Start Right sidebar -->
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4 sidebar-warp columns">
                        <div class="row">
                            <!-- Start post layout E -->
                            <aside class="zm-post-lay-e-area col-xs-12 col-sm-6 col-md-6 col-lg-12 hidden-md">
                                <div class="row mb-40">
                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                        <div class="section-title">
                                            <h2 class="h6 header-color inline-block uppercase">Most Popular</h2>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                        <div class="zm-posts">
                                            <?php foreach ($most_popular as $item) { ?>

                                                <!-- Start single post layout E -->
                                                <article class="zm-post-lay-e zm-single-post hidden-sm hidden-md clearfix">
                                                    <div class="zm-post-thumb f-left">
                                                        <a href="<?= Url::toRoute('news/' . $item['id_news'] . '-' . $item['alias']) ?>">
                                                            <?= Html::img('@web/images/news/' . $item['image'], ['alt' =>  $item['title']]) ?>
                                                        </a>
                                                    </div>
                                                    <div class="zm-post-dis f-right">
                                                        <div class="zm-post-header">
                                                            <h2 class="zm-post-title">
                                                                <a href="<?= Url::toRoute('news/' . $item['id_news'] . '-' . $item['alias']) ?>"><?= $item['title'] ?></a>
                                                            </h2>
                                                            <div class="zm-post-meta">
                                                                <ul>
                                                                    <li class="s-meta">Views: <?= $item['views'] ?></li>
                                                                    <li class="s-meta"><?= date('F d, Y', strtotime($item['date_publish'])) ?></li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </article>
                                                <!-- Start single post layout E -->
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </aside>
                            <!-- Start post layout E -->
                        </div>
                    </div>
                    <!-- End Right sidebar -->
                <?php } ?>
            </div>
            <!-- Start pagination area -->
            <div class="row hidden-xs">
                <div class="zm-pagination-wrap mt-70">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <nav class="zm-pagination ptb-40 text-center">
                                    <?= LinkPager::widget([
                                            'pagination' => $pagination,

                                            //Config for prev and next buttons
                                            'prevPageLabel' => 'PREVIOUS',
                                            'nextPageLabel' => 'NEXT',

                                            //Config pagination content wrapper
                                            'options' => [
                                                'tag' => 'ul',
                                                'class' => 'page-numbers',
                                            ],

                                            //Config class for page links
                                            'linkOptions' => ['class' => 'page-numbers'],
                                            'activePageCssClass' => 'current',
                                            'disabledPageCssClass' => 'btn-dpn',

                                            //Config css class for next and prev buttons
                                            'prevPageCssClass' => 'prev',
                                            'nextPageCssClass' => 'next',
                                    ])
                                    ?>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End pagination area -->
        </div>
    </div>
</section>
<!-- End page content -->

views/page/news_detail.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

?>

<!-- Start page content -->
<div id="page-content" class="page-wrapper">
    <div class="zm-section single-post-wrap bg-white ptb-70 xs-pt-30">
        <div class="container">
            <div class="row">
                <!-- Start left side -->
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 columns">

                    <div class="row">
                        <!-- Start single post image formate-->
                        <div class="col-md-12">
                            <article class="zm-post-lay-single">
                                <div class="zm-post-thumb">
                                    <?= Html::img('@web/images/news/' . $news['image'], ['alt' =>  $news['title']]) ?>

                                </div>
                                <div class="zm-post-dis">
                                    <div class="zm-post-header">
                                        <h2 class="zm-post-title h2"><?= $news['title'] ?></h2>
                                        <div class="zm-post-meta">
                                            <ul>
                                                <li class="s-meta">Views: <?= $news['views'] ?></li>
                                                <li class="s-meta"><?= date('F d, Y', strtotime($news['date_publish'])) ?></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="zm-post-content">
                                        <?= $news['content'] ?>
                                    </div>


                                </div>
                            </article>
                        </div>

                        <?php if (!empty($can_be_interesting)) { ?>
                            <!--Start Similar post -->
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ptb-40 mtb-40 border-top">
                                <aside class="zm-post-lay-a2-area">
                                    <div class="post-title mb-40">
                                        <h2 class="h6 inline-block">Can be intresting</h2>
                                    </div>
                                    <div class="row">
                                        <div class="zm-posts clearfix">
                                            <?php foreach ($can_be_interesting as $item) { ?>
                                                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                                                    <article class="zm-post-lay-a2">
                                                        <div class="zm-post-thumb">
                                                            <a href="<?= Url::toRoute('news/' . $item['id_news'] . '-' . $item['alias']) ?>">
                                                                <?= Html::img('@web/images/news/' . $item['image'], ['alt' =>  $item['title']]) ?>
                                                            </a>
                                                        </div>
                                                        <div class="zm-post-dis">
                                                            <div class="zm-post-header">
                                                                <h2 class="zm-post-title h2">
                                                                    <a href="<?= Url::toRoute('news/' . $item['id_news'] . '-' . $item['alias']) ?>"><?= $item['title'] ?></a>
                                                                </h2>
                                                                <div class="zm-post-meta">
                                                                    <ul>
                                                                        <li class="s-meta">Views: <?= $item['views'] ?></li>
                                                                        <li class="s-meta"><?= date('F d, Y', strtotime($item['date_publish'])) ?></li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </article>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </aside>
                            </div>
                            <!-- End similar post -->
                        <?php } ?>
                    </div>
                </div>
                <!-- End left side -->

                <?php if (!empty($most_popular)) { ?>
                    <!-- Start Right sidebar -->
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 sidebar-warp columns">
                        <div class="row">
                            <!-- Start post layout E -->
                            <aside class="zm-post-lay-e-area col-sm-6 col-md-12 col-lg-12">
                                <div class="row mb-40">
                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                        <div class="section-title">
                                            <h2 class="h6 header-color inline-block uppercase">Most Popular</h2>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                        <div class="zm-posts">

                                            <?php foreach ($most_popular as $item) { ?>
                                                <!-- Start single post layout E -->
                                                <article class="zm-post-lay-e zm-single-post hidden-sm hidden-md clearfix">
                                                    <div class="zm-post-thumb f-left">
                                                        <a href="<?= Url::toRoute('news/' . $item['id_news'] . '-' . $item['alias']) ?>">
                                                            <?= Html::img('@web/images/news/' . $item['image'], ['alt' =>  $item['title']]) ?>
                                                        </a>
                                                    </div>
                                                    <div class="zm-post-dis f-right">
                                                        <div class="zm-post-header">
                                                            <h2 class="zm-post-title">
                                                                <a href="<?= Url::toRoute('news/' . $item['id_news'] . '-' . $item['alias']) ?>"><?= $item['title'] ?></a>
                                                            </h2>
                                                            <div class="zm-post-meta">
                                                                <ul>
                                                                    <li class="s-meta">Views: <?= $item['views'] ?></li>
                                                                    <li class="s-meta"><?= date('F d, Y', strtotime($item['date_publish'])) ?></li>
                                                                </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </article>
                                                <!-- Start single post layout E -->
                                            <?php } ?>

                                        </div>
                                    </div>
                                </div>
                            </aside>
                            <!-- End post layout E -->

                        </div>
                    </div>
                    <!-- End Right sidebar -->
                <?php } ?>

            </div>
        </div>
    </div>
</div>
<!-- End page content -->